package id.ac.poliban.mi.sari.listviewpahlawan;

import java.util.ArrayList;
import java.util.List;

public class HeroData {
    static List<Hero> getAllHeroes(){
        List<Hero> data = new ArrayList<>();
        {
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Panglima_Pol%C3%A8m_II.jpg/150px-Panglima_Pol%C3%A8m_II.jpg", "Panglima Polem IX", "Panglima Polem bernama lengkap Teuku Panglima Polem Sri Muda Perkasa Muhammad Daud adalah seorang panglima Aceh. Sampai saat ini belum ditemukan keterangan yang jelas mengenai tanggal dan tahun kelahiran Panglima Polem, yang jelas ia berasal dari keturunan kaum bangsawan Aceh. Ayahnya bernama Panglima Polem VIII Raja Kuala anak dari Teuku Panglima Polem Sri Imam Muda Mahmud Arifin yang juga terkenal dengan Cut Banta (Panglima Polem VII (1845-1879). "));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Teuku_Umar.jpg/200px-Teuku_Umar.jpg", "Teuku Umar", "Teuku Umar (Meulaboh, 1854 - Meulaboh, 11 Februari 1899) adalah pahlawan asal Aceh yang berjuang dengan cara berpura-pura bekerjasama dengan Belanda & terkenal akan strategi perang gerilyanya. Ia melawan Belanda ketika telah mengumpulkan senjata dan uang yang cukup banyak."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg/220px-Ki_Hadjar_Dewantara_Mimbar_Umum_18_October_1949_p2.jpg", "Ki hajar Dewantara", "Raden Mas Soewardi Soerjaningrat (EBI: Suwardi Suryaningrat, sejak 1922 menjadi Ki Hadjar Dewantara, EBI: Ki Hajar Dewantara, beberapa menuliskan bunyi bahasa Jawanya dengan Ki Hajar Dewantoro; lahir di Pakualaman, 2 Mei 1889 – meninggal di Yogyakarta, 26 April 1959 pada umur 69 tahun;[1] selanjutnya disingkat sebagai \"Soewardi\" atau \"KHD\") adalah aktivis pergerakan kemerdekaan Indonesia, kolumnis, politisi, dan pelopor pendidikan bagi kaum pribumi Indonesia dari zaman penjajahan Belanda. Ia adalah pendiri Perguruan Taman Siswa, suatu lembaga pendidikan yang memberikan kesempatan bagi para pribumi untuk bisa memperoleh hak pendidikan seperti halnya para priyayi maupun orang-orang Belanda."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Tjoet_Nya%27_Dhien.jpg/220px-Tjoet_Nya%27_Dhien.jpg", "Cut Nyak Dhien", "Cut Nyak Dhien (ejaan lama: Tjoet Nja' Dhien, Lampadang, Kerajaan Aceh, 1848 – Sumedang, Jawa Barat, 6 November 1908; dimakamkan di Gunung Puyuh, Sumedang) adalah seorang Pahlawan Nasional Indonesia dari Aceh yang berjuang melawan Belanda pada masa Perang Aceh. Setelah wilayah VI Mukim diserang, ia mengungsi, sementara suaminya Ibrahim Lamnga bertempur melawan Belanda. Tewasnya Ibrahim Lamnga di Gle Tarum pada tanggal 29 Juni 1878 kemudian menyeret Cut Nyak Dhien lebih jauh dalam perlawanannya terhadap Belanda."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Bung_Tomo.jpg/220px-Bung_Tomo.jpg", "Sutomo", "Sutomo (lahir di Surabaya, Jawa Timur, 3 Oktober 1920 – meninggal di Padang Arafah, Arab Saudi, 7 Oktober 1981 pada umur 61 tahun)[1] lebih dikenal dengan sapaan akrab oleh rakyat sebagai Bung Tomo, adalah pahlawan yang terkenal karena peranannya dalam membangkitkan semangat rakyat untuk melawan kembalinya penjajah Belanda melalui tentara NICA, yang berakhir dengan pertempuran 10 November 1945 yang hingga kini diperingati sebagai Hari Pahlawan."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg/200px-COLLECTIE_TROPENMUSEUM_Portret_van_Raden_Ajeng_Kartini_TMnr_10018776.jpg", "R.A. Kartini", "Raden Adjeng Kartini (lahir di Jepara, Hindia Belanda, 21 April 1879 – meninggal di Rembang, Hindia Belanda, 17 September 1904 pada umur 25 tahun) atau sebenarnya lebih tepat disebut Raden Ayu Kartini[1] adalah seorang tokoh Jawa dan Pahlawan Nasional Indonesia. Kartini dikenal sebagai pelopor kebangkitan perempuan pribumi."));
            data.add(new Hero("https://upload.wikimedia.org/wikipedia/id/1/17/Pattimura_2.jpg", "Pattimura", "Pattimura (Thomas Matulessy) lahir di Haria, pulau Saparua, Maluku, 8 Juni 1783 – meninggal di Ambon, Maluku, 16 Desember 1817 pada umur 34 tahun), juga dikenal dengan nama Kapitan Pattimura adalah Pahlawan nasional Indonesia dari Maluku.\n" +
                    "\n" +
                    "Menurut buku biografi Pattimura versi pemerintah yang pertama kali terbit, M Sapija menulis, \"Bahwa pahlawan Pattimura tergolong turunan bangsawan dan berasal dari Nusa Ina (Seram)\". Ayahnya yang bernama Antoni Matulessy adalah anak dari Kasimiliali Pattimura Mattulessy. Yang terakhir ini adalah putra raja Sahulau. Sahulau merupakan nama orang di negeri yang terletak dalam sebuah teluk di Seram."));
        }
        return data;
    }
}
